import Navbar from "@/components/navbar/navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Footer from "@/components/footer/footer";

const poppins = Poppins({
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
	subsets: ["latin"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "Drawr",
	description: "Generated by create next app",
	icons: { apple: "/apple-touch-icon.png", icon: "" },
	viewport: { width: "device-width", initialScale: 1 },
	openGraph: {
		type: "website",
		url: "https://drawr.com",
		title: "Drawr",
		description: "",
		siteName: "Drawr",
		locale: "en_UK",
	},
	twitter: {
		creator: "@drawr",
		card: "summary_large_image",
	},
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={poppins.className}>
				<Navbar />
				{children}
				{/* <Footer /> */}
			</body>
		</html>
	);
}
